### ISSUE TITLE
definir notificaciones push

### ISSUE THREAD

**Issue by rburdet** [NickCis/7552-taller-prog-2-2015-C1#10]
Definir como serian las notificaciones push
Implementación en ambos lados

**Comment by NickCis** [comment]
Se puede usar el estandar de las [server sent events](http://www.html5rocks.com/en/tutorials/eventsource/basics/). Basicamente es que el servidor no cierre la connecion y mande info por ahi por cada nueva notitificacion.

**Comment by NickCis** [comment]
Se escribe la especificaci&oacute;n de las notificaciones push: [wiki](https://github.com/NickCis/7552-taller-prog-2-2015-C1/wiki/Notificaciones#lectura-push) Se utiliza SSE
