### ISSUE TITLE
Definir logging

### ISSUE THREAD

**Issue by NickCis** [NickCis/7552-taller-prog-2-2015-C1#16]
Definir una herramienta para loggear, la sintaxis podria ser parecida a la que usa qDebug() ( se puede usar de base esta: [.h](https://github.com/NickCis/whats-acppi/blob/master/src/util/log.h) y [.cpp](https://github.com/NickCis/whats-acppi/blob/master/src/util/log.cpp)

Recordar que el enunciado pide estos niveles de log:
- Error
- Warn
- Info
- Debug

**Comment by NickCis** [comment]
Estaria bueno que cuando arranca el servidor loggee cuando fue compilado, la version, version de mongoose, y hash de revision del git.

**Comment by martindonofrio** [comment]
Propongo log4cpp para el server y log4J para el cliente.
