### ISSUE TITLE
Crear una estructura de datos para soportar almacenamiento parcial

### ISSUE THREAD

**Issue by MatSebMan** [NickCis/7552-taller-prog-2-2015-C1#22]
Crear una estructura de datos interna para almacenar en el dispositivo conversaciones activas y mensajes de las mismas hasta cierto punto para un rápido acceso a ellas. El resto del historial será cargado del servidor a pedido.

**Comment by NickCis** [comment]
@rburdet @MatSebMan  Me parece que este es un duplicado de #12 .

**Comment by MatSebMan** [comment]
Así parece. Mi error.

**Comment by NickCis** [comment]
Borren uno de los dos :)
