### ISSUE TITLE
Documentacion de codigo (comenten el codigo)

### ISSUE THREAD

**Issue by martindonofrio** [NickCis/7552-taller-prog-2-2015-C1#42]
Para poder armar la documentación de código debemos ir comentando el código que subimos.

Podemos usar Doxygen en el cliente y en el server, la sintaxis es la misma de javadocs.

Comentar clases y métodos usando los tags de javadocs, author, param, etc.

**Comment by NickCis** [comment]
Hay que documentar estilo doxygen, creo qe el enunciado lo pedia asi,,
@rburdet 
@MatSebMan
