### ISSUE TITLE
Decidir framework para tests

### ISSUE THREAD

**Issue by NickCis** [NickCis/7552-taller-prog-2-2015-C1#5]

**Comment by martindonofrio** [comment]
Se avanzo con esto?

Que les parece CUTE?.

**Comment by NickCis** [comment]
Vamos a usar este: https://github.com/cpputest/cpputest solo por qe es el unico qe [**no** tiene una web qe no parece haber estado hecha en los 90](http://cpputest.github.io/)

**Comment by NickCis** [comment]
Como siempre los frameworks para test son un cancer,, Voy a usar [catch](https://github.com/philsquared/Catch/) por que solo hay que incluir un .h
