### ISSUE TITLE
agregar username a notification de checkin

### ISSUE THREAD

**Issue by rburdet** [NickCis/7552-taller-prog-2-2015-C1#85]
Cuando llegue una notification tiene que venir un campo con el username de quien fue el que activo esa notificacion

**Comment by NickCis** [comment]
Se corrige protocolo: [`Notificacion/ checkin`](https://github.com/NickCis/7552-taller-prog-2-2015-C1/wiki/Notificaciones#typecheckin) y [`/user/<usuario>/checkin`](https://github.com/NickCis/7552-taller-prog-2-2015-C1/wiki/Usuarios-Checkin#respuesta)
